//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int Id { get; set; }
        public int RoomCount { get; set; }
        public int TypeId { get; set; }
        public int Price { get; set; }
        public System.DateTime AvailabilityDate { get; set; }
        public string Owner { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
